### ISSUE TITLE
Open calculator doesn't show all calc apps

### ISSUE THREAD

**Issue by MartinL0815** [simonesestito/nougat_quickSettings#15]
Two calc apps of four are listed. What may be the reason?

**Comment by simonesestito** [comment]
Hi! Could you tell me the package names of all the calculator apps?

**Comment by MartinL0815** [comment]
How do I get the package names?
I miss Droid48 and NeoCal

**Comment by MartinL0815** [comment]
The listed ones are MyScript calculator and the system calculator

**Comment by simonesestito** [comment]
Android doesn't expose an API to list calculator apps, so the trick used by the app is to list all apps installed with "calc" in their name. Using "cal" instead would list your other 2 apps but it's more likely to show other non-calculator apps
