### ISSUE TITLE
Open files browser doesn't open default app

### ISSUE THREAD

**Issue by MartinL0815** [simonesestito/nougat_quickSettings#16]
I configured XPlore to be the default files browser app, but your tile doesn't open the default app (Sony Xperia XS21 compact; Oreo)

**Comment by simonesestito** [comment]
It should open the system file manager. Doesn't it?

**Comment by MartinL0815** [comment]
It opens a file browser, the one my mail app is to attach files. But not the default/standard file browser

**Comment by simonesestito** [comment]
It can't use your default file manager. It uses the system default one, same behavior as the mail app.

If you want to launch your favorite file manager app, use an "App & Shortcut" tile instead
