### ISSUE TITLE
Screenshot tile uses 12h instead of 24h time format

### ISSUE THREAD

**Issue by Susko3** [simonesestito/nougat_quickSettings#17]
Example: screenshot taken at 18:49 has the name "Screenshot_2018_08_21_06_49_15.jpg". This is an issue because when sorting by name, screenshots are in wrong order and because there could be duplicates (screenshots taken at 7:00:00 and 19:00:00 would have the same name)

**Comment by simonesestito** [comment]
What's the language on your phone? On the system click in status bar, do you see 12h or 24h format?

**Comment by Susko3** [comment]
I have 24 hour format on status bar

**Comment by simonesestito** [comment]
Good news, I found the cause of this bug in the code and I'm able to fix it soon. Thanks for the report
