### ISSUE TITLE
tiles get removed after reboot in pie

### ISSUE THREAD

**Issue by raviandroid97** [simonesestito/nougat_quickSettings#27]
After reboot all tiles are removed from quick settings. And after every reboot i have to set all tiles again in android pie.

**Comment by simonesestito** [comment]
Could you tell me what is your phone?
It works perfectly on every phone I tested it on, running Android Pie

**Comment by raviandroid97** [comment]
It's Nokia 5 (2017) version, updated to pie.

**Comment by raviandroid97** [comment]
I think I have found the reason for this. This may be system problem, because this happens when app is installed on external SD card formatted as internal storage. When app is installed on internal storage, it works fine.

**Comment by simonesestito** [comment]
Thanks a lot for the clarification!
