### ISSUE TITLE
Can you please add customizable default Calculator app?

### ISSUE THREAD

**Issue by Hexaae** [simonesestito/nougat_quickSettings#28]
Current QS searches for user installed apps named "calc", but if you want the Calculator qs to quickly open the default Calculator app you can't set it as default (and don't like bottom panel to choose which one to launch among all "calc" apps installed)... turning this in a slow-setting ;)
Can you please add a default setting to define 1 app only for the Calculator qs?
I know I can create a specific app shortcut (with ugly automatically generated icon) but it would be much better if we had the choice to select the default app for every default category...

**Comment by simonesestito** [comment]
Closed for the same reason as #29
