### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Fruity-0** [simonesestito/nougat_quickSettings#32]
Hello. Can I translate the language file into my native language and possibly send for implementation in the next update ?

**Comment by simonesestito** [comment]
Hi. Yes, you can.

Il dom 30 ago 2020, 04:51 Fruity <notifications@github.com> ha scritto:

**Comment by Fruity-0** [comment]
Hello, I am uploading the translation file to GitHub and e-mail too. When I check the application, I will add some corrections. In case there are coding errors please let me know.

[LINK](http://31.6.70.6/pliki/newtone/pliki/stringsQuickSeting-%20PL.zip)
