### ISSUE TITLE
Tap tap tile request

### ISSUE THREAD

**Issue by AxiK101** [simonesestito/nougat_quickSettings#4]
Can you include this tile plzz???![](https://i.imgur.com/O8Fhx3f.png)![](https://i.imgur.com/8yEsAoJ.png)

**Comment by simonesestito** [comment]
I never used that app but it looks like an option to enable/disable "Show touches" like dev options. If is it, I can  add in the next release. it's very easy to do, good idea

**Comment by AxiK101** [comment]
yes!! thanks so much. btw the icon that franco use is quite nice. I don't say to add the exact same but a similar would be great.

**Comment by AxiK101** [comment]
![](https://i.imgur.com/FnTmWEu.png)
![](https://i.imgur.com/MsBopfY.png)

**Comment by simonesestito** [comment]
This icon can be used
https://materialdesignicons.com/icon/gesture-double-tap

**Comment by AxiK101** [comment]
Just saw the new how-to video! Thanks for adding this tile! Let's wait for the roll on!
