### ISSUE TITLE
"ON - " and "OFF - " prefixes for 'auto brightness' and 'night mode'

### ISSUE THREAD

**Issue by kcpr** [simonesestito/nougat_quickSettings#6]
What are those prefixes for? They are not included in translated strings, but are still displayed.

**Comment by simonesestito** [comment]
They are a workaround for a bug of Android 7.1 which doesn't display the correct state of the toggles, so I decided to add this workaround. With that you can know the correct state of the toggle, also when Android doesn't change its colour

**Comment by kcpr** [comment]
Ok, I understand. Could You add an option in settings to disable it? That would be great.

**Comment by simonesestito** [comment]
It's pointless. For example, with Auto Brighteness, you will be unable to know if it's enabled or not with the toggle. Why should someone disable it?

**Comment by kcpr** [comment]
I do not experience the bug You described often and I usually know when I have got Auto Brightness on, so I just don't need extra information about it.
